name: ci
on: [push, pull_request]
# on:
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]
jobs:
  simple_make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get install -y python-gobject-2-dev libgtk-3-dev
      - run: ./configure
      - run: make
      - run: make check
      - run: make install
  complex_make:
    strategy:
      fail-fast: false
      matrix:
        LUA_FLAG: ["", "--without-liblua"]
        SSL_FLAG: ["", "--without-openssl"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get install -y python-gobject-2-dev libgtk-3-dev
      - run: |
          mkdir /tmp/n
          ./configure ${{ matrix.SSL_FLAG }} ${{ matrix.LUA_FLAG }} --prefix=/tmp/n
          make
          make check
          make install
          /tmp/n/bin/nmap -A localhost
